/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TPV.GUI;

import TPV.Clases.GestionBDRegistro;
import TPV.Clases.Producto;
import TPV.Clases.Usuario;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Jairo
 */
public class AdminNuevo extends javax.swing.JFrame {

    int switchUsuarios;
    int switchProductos;
    int botonOk = 0; // si es 1 aceptará usuarios, si pulsa 0 aceptará productos
    DefaultListModel model;
    GestionBDRegistro gest = new GestionBDRegistro("root", "", "sandwichdb", "localhost");

    /**
     * Creates new form GUIs
     */
    public void windowClosing(WindowEvent e) {
        System.exit(0);
    }

    /**
     * Creates new form AdminNuevo
     */
    public AdminNuevo() {
        initComponents();
        this.setResizable(false);
        this.PanelUsuario.setVisible(false);
        this.PanelProducto.setVisible(false);
        this.jFileChooser1.setVisible(false);
        this.setLocationRelativeTo(null);
        this.PanelProducto.setVisible(true);

    }

    public void cargarUnUsuario() throws SQLException, ClassNotFoundException {

        Usuario usu = gest.buscarUsuario(Integer.parseInt(this.usuarioId.getText()));
        model = new DefaultListModel();
        if (usu.getIdUsuario()!= 0) {
            model.addElement("<html>"
                    + "Id Empleado: " + usu.getIdUsuario()
                    + "<br> Nombre: " + usu.getNombre()
                    + "<br> Password: " + usu.getPass()
                    + "<br> Administrador: " + usu.getAdmin() + "</html>");
            resultadoBusqueda.setModel(model);
        } else {

            String mensaje = String.format("<html><h2>No existe el empleado con numero: %s </h2></html>", this.usuarioId.getText());
            JOptionPane.showMessageDialog(this, mensaje);
        }
    }
    
    public void cargarUnProducto() throws SQLException, ClassNotFoundException {

        Producto prod = gest.buscarProducto(Integer.parseInt(this.productoId.getText()));
        model = new DefaultListModel();
        if (prod.getIdProducto()!= 0) {
            model.addElement("<html>"
                    + "Id Producto: " + prod.getIdProducto()
                    + "<br> Nombre: " + prod.getNombre()
                    + "<br> Stock: " + prod.getStock()
                    + "<br> Precio: " + prod.getPrecio()
                    + "<br> imagen " + prod.getRutaImg()+ "</html>");
            resultadoBusqueda.setModel(model);
        } else {

            String mensaje = String.format("<html><h2>No existe el producto con numero: %s </h2></html>", this.productoId.getText());
            JOptionPane.showMessageDialog(this, mensaje);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbProductos = new javax.swing.ButtonGroup();
        rbUsuarios = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnTPV = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        PanelUsuario = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        usuarioNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AdminId1 = new javax.swing.JLabel();
        usuarioId = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        usuarioPass = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jRadioModificarUsuario = new javax.swing.JRadioButton();
        jRadioBuscarUsuario = new javax.swing.JRadioButton();
        jRInsertarUsuario = new javax.swing.JRadioButton();
        jRadioEliminarUsuario = new javax.swing.JRadioButton();
        PanelProducto = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jRadioInsertarProducto = new javax.swing.JRadioButton();
        jRadioEliminarProducto = new javax.swing.JRadioButton();
        jRadioModificarProducto = new javax.swing.JRadioButton();
        jRadioBuscarProducto = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AdminId = new javax.swing.JLabel();
        productoStock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        productoPrecio = new javax.swing.JTextField();
        productoNombre = new javax.swing.JTextField();
        btnBuscarImagen = new javax.swing.JButton();
        productoId = new javax.swing.JTextField();
        rutaImagen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jBOk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultadoBusqueda = new javax.swing.JList<>();
        btnInformes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenesTpv/logoPeque.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        btnUsuario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnUsuario.setText("Usuarios");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        btnProductos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnTPV.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnTPV.setText("TPV");
        btnTPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTPVActionPerformed(evt);
            }
        });

        btnCerrar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        usuarioNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("PassWord: ");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Administrador: ");

        AdminId1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        AdminId1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AdminId1.setText("Id Usuario: ");

        usuarioId.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jCheckBox2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jCheckBox2.setText(" Pulsa para permisos de Administrador");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre Usuario: ");

        usuarioPass.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminId1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioId)
                    .addComponent(usuarioNombre)
                    .addComponent(usuarioPass)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuarioId)
                    .addComponent(AdminId1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuarioNombre)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuarioPass)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        rbUsuarios.add(jRadioModificarUsuario);
        jRadioModificarUsuario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jRadioModificarUsuario.setText("Modificar");
        jRadioModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioModificarUsuarioActionPerformed(evt);
            }
        });

        rbUsuarios.add(jRadioBuscarUsuario);
        jRadioBuscarUsuario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jRadioBuscarUsuario.setText("Buscar");
        jRadioBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBuscarUsuarioActionPerformed(evt);
            }
        });

        rbUsuarios.add(jRInsertarUsuario);
        jRInsertarUsuario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jRInsertarUsuario.setText("Insertar");
        jRInsertarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRInsertarUsuarioActionPerformed(evt);
            }
        });

        rbUsuarios.add(jRadioEliminarUsuario);
        jRadioEliminarUsuario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jRadioEliminarUsuario.setText("Eliminar");
        jRadioEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEliminarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRInsertarUsuario)
                .addGap(18, 18, 18)
                .addComponent(jRadioModificarUsuario)
                .addGap(18, 18, 18)
                .addComponent(jRadioEliminarUsuario)
                .addGap(18, 18, 18)
                .addComponent(jRadioBuscarUsuario)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRInsertarUsuario)
                    .addComponent(jRadioModificarUsuario)
                    .addComponent(jRadioEliminarUsuario)
                    .addComponent(jRadioBuscarUsuario))
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelUsuarioLayout = new javax.swing.GroupLayout(PanelUsuario);
        PanelUsuario.setLayout(PanelUsuarioLayout);
        PanelUsuarioLayout.setHorizontalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelUsuarioLayout.setVerticalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        rbProductos.add(jRadioInsertarProducto);
        jRadioInsertarProducto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jRadioInsertarProducto.setText("Insertar");
        jRadioInsertarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioInsertarProductoActionPerformed(evt);
            }
        });

        rbProductos.add(jRadioEliminarProducto);
        jRadioEliminarProducto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jRadioEliminarProducto.setText("Eliminar");
        jRadioEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEliminarProductoActionPerformed(evt);
            }
        });

        rbProductos.add(jRadioModificarProducto);
        jRadioModificarProducto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jRadioModificarProducto.setText("Modificar");
        jRadioModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioModificarProductoActionPerformed(evt);
            }
        });

        rbProductos.add(jRadioBuscarProducto);
        jRadioBuscarProducto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jRadioBuscarProducto.setText("Buscar");
        jRadioBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBuscarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioInsertarProducto)
                .addGap(18, 18, 18)
                .addComponent(jRadioModificarProducto)
                .addGap(18, 18, 18)
                .addComponent(jRadioEliminarProducto)
                .addGap(18, 18, 18)
                .addComponent(jRadioBuscarProducto)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioInsertarProducto)
                    .addComponent(jRadioModificarProducto)
                    .addComponent(jRadioEliminarProducto)
                    .addComponent(jRadioBuscarProducto))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre Producto: ");

        AdminId.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        AdminId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AdminId.setText("Id Producto: ");

        productoStock.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Precio: ");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Imagen: ");

        productoPrecio.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        productoPrecio.setHighlighter(null);

        productoNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        btnBuscarImagen.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnBuscarImagen.setText("Buscar");
        btnBuscarImagen.setFocusTraversalPolicyProvider(true);
        btnBuscarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarImagenActionPerformed(evt);
            }
        });

        productoId.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        rutaImagen.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Stock: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdminId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productoId)
                    .addComponent(productoNombre)
                    .addComponent(productoStock)
                    .addComponent(productoPrecio)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBuscarImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(rutaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(productoId)
                    .addComponent(AdminId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(productoNombre)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(productoStock)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBuscarImagen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rutaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelProductoLayout = new javax.swing.GroupLayout(PanelProducto);
        PanelProducto.setLayout(PanelProductoLayout);
        PanelProductoLayout.setHorizontalGroup(
            PanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductoLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelProductoLayout.setVerticalGroup(
            PanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLayeredPane1.setLayer(PanelUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(PanelProducto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PanelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(PanelProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(387, 387, 387)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(378, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(308, 308, 308)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );

        jBOk.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBOk.setText("OK");
        jBOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOkActionPerformed(evt);
            }
        });

        resultadoBusqueda.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jScrollPane1.setViewportView(resultadoBusqueda);

        btnInformes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnInformes.setText("Informes");
        btnInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnInformes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTPV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(jBOk, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBOk, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTPV, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        this.PanelUsuario.setVisible(false);
        this.PanelProducto.setVisible(true);
        botonOk = 1;
        this.productoId.setBackground(Color.white);
        this.productoNombre.setBackground(Color.white);
        this.productoPrecio.setBackground(Color.white);
        this.productoStock.setBackground(Color.white);

    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        this.PanelUsuario.setVisible(true);
        this.PanelProducto.setVisible(false);
        botonOk = 0;
        this.usuarioId.setBackground(Color.white);
        this.usuarioNombre.setBackground(Color.white);
        this.usuarioPass.setBackground(Color.white);
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void jRInsertarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRInsertarUsuarioActionPerformed
        switchUsuarios = 0;
        this.usuarioId.setEnabled(true);
        this.usuarioNombre.setEnabled(true);
        this.usuarioPass.setEnabled(true);
        this.jCheckBox2.setEnabled(true);
    }//GEN-LAST:event_jRInsertarUsuarioActionPerformed

    private void jRadioModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioModificarUsuarioActionPerformed
        switchUsuarios = 1;
        this.usuarioId.setEnabled(true);
        this.usuarioNombre.setEnabled(true);
        this.usuarioPass.setEnabled(true);
        this.jCheckBox2.setEnabled(true);
    }//GEN-LAST:event_jRadioModificarUsuarioActionPerformed

    private void jRadioEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEliminarUsuarioActionPerformed
        switchUsuarios = 2;
        this.usuarioId.setEnabled(true);
        this.usuarioNombre.setEnabled(false);
        this.usuarioPass.setEnabled(false);
        this.jCheckBox2.setEnabled(false);
    }//GEN-LAST:event_jRadioEliminarUsuarioActionPerformed

    private void jRadioBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBuscarUsuarioActionPerformed
        switchUsuarios = 3;
        this.usuarioId.setEnabled(true);
        this.usuarioNombre.setEnabled(false);
        this.usuarioPass.setEnabled(false);
        this.jCheckBox2.setEnabled(false);
    }//GEN-LAST:event_jRadioBuscarUsuarioActionPerformed

    private void jBOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOkActionPerformed
        if (botonOk == 0) {
            int administrador = 0;

            switch (switchUsuarios) {
                case 0:

                    if (this.usuarioId.getText().isEmpty() == false
                            && this.usuarioNombre.getText().isEmpty() == false
                            && this.usuarioPass.getText().isEmpty() == false) {

                        Integer idUsuario = Integer.parseInt(this.usuarioId.getText()); // error NumberFormatException solucionamos
                        Integer passWord = Integer.parseInt(this.usuarioPass.getText());
                        if (this.jCheckBox2.isSelected()) {
                            administrador = 1;
                        }
                        Usuario nuevoUsuario = new Usuario(
                                idUsuario,
                                passWord,
                                this.usuarioNombre.getText(),
                                administrador
                        );

                        gest.insertarUsuario(nuevoUsuario);
                        JOptionPane.showMessageDialog(this, "<html><h3>Usuario Insertado</h3></html>");
                        this.usuarioId.setText("");
                        this.usuarioNombre.setText("");
                        this.usuarioPass.setText("");

                    } else {

                        if (this.usuarioId.getText().isEmpty() == true) {
                            this.usuarioId.setBackground(Color.yellow);
                        } else {
                            this.usuarioId.setBackground(Color.white);
                        }
                        if (this.usuarioNombre.getText().isEmpty() == true) {
                            this.usuarioNombre.setBackground(Color.yellow);
                        } else {
                            this.usuarioNombre.setBackground(Color.white);
                        }
                        if (this.usuarioPass.getText().isEmpty() == true) {
                            this.usuarioPass.setBackground(Color.yellow);
                        } else {
                            this.usuarioPass.setBackground(Color.white);
                        }

                        JOptionPane.showMessageDialog(this, "<html><h3>Error al insertar Usuario, por favor,<br> revise los campos sin rellenar </h3></html>");

                    }

                    break;

                case 1:
                    if (this.usuarioId.getText().isEmpty() == false
                            && this.usuarioNombre.getText().isEmpty() == false
                            && this.usuarioPass.getText().isEmpty() == false) {

                        Integer idUsuario = Integer.parseInt(this.usuarioId.getText()); // error NumberFormatException solucionamos
                        Integer passWord = Integer.parseInt(this.usuarioPass.getText());
                        if (this.jCheckBox2.isSelected()) {
                            administrador = 1;
                        }
                        Usuario nuevoUsuario = new Usuario(
                                idUsuario,
                                passWord,
                                this.usuarioNombre.getText(),
                                administrador
                        );

                        gest.modificarUsuario(nuevoUsuario);
                        JOptionPane.showMessageDialog(this, "<html><h3>Usuario Modificado</h3></html>");
                        this.usuarioId.setText("");
                        this.usuarioNombre.setText("");
                        this.usuarioPass.setText("");

                    } else {

                        if (this.usuarioId.getText().isEmpty() == true) {
                            this.usuarioId.setBackground(Color.yellow);
                        } else {
                            this.usuarioId.setBackground(Color.white);
                        }
                        if (this.usuarioNombre.getText().isEmpty() == true) {
                            this.usuarioNombre.setBackground(Color.yellow);
                        } else {
                            this.usuarioNombre.setBackground(Color.white);
                        }
                        if (this.usuarioPass.getText().isEmpty() == true) {
                            this.usuarioPass.setBackground(Color.yellow);
                        } else {
                            this.usuarioPass.setBackground(Color.white);
                        }

                        JOptionPane.showMessageDialog(this, "<html><h3>Error al Modificar Usuario, por favor,<br> revise los campos sin rellenar </h3></html>");

                    }
                    break;

                case 2:
                    if (this.usuarioId.getText().isEmpty() == false) {
                        Integer IdAdmin = Integer.parseInt(this.usuarioId.getText());
                        Usuario UsuarioBorrar = new Usuario(IdAdmin);
                        {
                            gest.borrarUsuario(UsuarioBorrar);
                            JOptionPane.showMessageDialog(this, "<html><h3>Usuario Eliminado</h3></html>");
                            this.usuarioId.setText("");
                            this.usuarioNombre.setText("");
                            this.usuarioPass.setText("");
                        }
                    } else {
                        if (this.usuarioId.getText().isEmpty() == true) {
                            this.usuarioId.setBackground(Color.yellow);
                        } else {
                            this.usuarioId.setBackground(Color.white);
                        }

                        JOptionPane.showMessageDialog(this, "<html><h3>Error al eliminar Usuario, por favor,<br> intrudzca un valor válido </h3></html>");

                    }
                    break;

                case 3:
                    if (this.usuarioId.getText().isEmpty() == false) {
                        Integer idUsu = Integer.parseInt(this.usuarioId.getText());

                        {
                            gest.buscarUsuario(idUsu);
                            try {
                                this.cargarUnUsuario();
                            } catch (SQLException | ClassNotFoundException ex) {
                                Logger.getLogger(AdminNuevo.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            this.usuarioId.setText("");
                            this.usuarioNombre.setText("");
                            this.usuarioPass.setText("");
                        }
                    } else {
                        if (this.usuarioId.getText().isEmpty() == true) {
                            this.usuarioId.setBackground(Color.yellow);
                        } else {
                            this.usuarioId.setBackground(Color.white);
                        }

                        JOptionPane.showMessageDialog(this, "<html><h3>Error al encontrar Usuario, por favor,<br> intrudzca un valor válido </h3></html>");

                    }
                    break;
            }
        } else if (botonOk == 1) {
            switch (switchProductos) {
                case 0:

                    if (this.productoId.getText().isEmpty() == false
                            && this.productoNombre.getText().isEmpty() == false
                            && this.productoStock.getText().isEmpty() == false
                            && this.productoPrecio.getText().isEmpty() == false
                            && this.rutaImagen.getText().isEmpty() == false){

                        Integer IdProd = Integer.parseInt(this.productoId.getText());
                        Integer stock = Integer.parseInt(this.productoStock.getText());
                        float precioProd = Float.parseFloat(this.productoPrecio.getText());
                        Producto nuevoProducto = new Producto(
                                IdProd,
                                stock,
                                this.productoNombre.getText(),
                                this.rutaImagen.getText(),
                                precioProd
                        );

                        gest.insertarProducto(nuevoProducto);
                        JOptionPane.showMessageDialog(this, "<html><h3>Producto Insertado</h3></html>");
                        this.productoNombre.setText("");
                        this.productoId.setText("");
                        this.productoStock.setText("");
                        this.productoPrecio.setText("");
                        this.rutaImagen.setText("");

                    } else {

                        if (this.productoNombre.getText().isEmpty() == true) {
                            this.productoNombre.setBackground(Color.yellow);
                        } else {
                            this.productoNombre.setBackground(Color.white);
                        }
                        if (this.productoId.getText().isEmpty() == true) {
                            this.productoId.setBackground(Color.yellow);
                        } else {
                            this.productoId.setBackground(Color.white);
                        }
                        if (this.productoStock.getText().isEmpty() == true) {
                            this.productoStock.setBackground(Color.yellow);
                        } else {
                            this.productoStock.setBackground(Color.white);
                        }
                        if (this.productoPrecio.getText().isEmpty() == true) {
                            this.productoPrecio.setBackground(Color.yellow);
                        } else {
                            this.productoPrecio.setBackground(Color.white);
                        }
                        if (this.rutaImagen.getText().isEmpty() == true) {
                            this.rutaImagen.setBackground(Color.yellow);
                        } else {
                            this.rutaImagen.setBackground(Color.white);
                        }

                        JOptionPane.showMessageDialog(this, "<html><h3>Error al insertar Producto, por favor,<br> revise los campos sin rellenar </h3></html>");

                    }

                    break;

                case 1:
                    if (this.productoNombre.getText().isEmpty() == false
                            && this.productoId.getText().isEmpty() == false
                            && this.productoStock.getText().isEmpty() == false
                            && this.productoPrecio.getText().isEmpty() == false
                            && this.rutaImagen.getText().isEmpty() == false) {

                        Integer IdProd = Integer.parseInt(this.productoId.getText());
                        Integer stock = Integer.parseInt(this.productoStock.getText());
                        float precioProd = Float.parseFloat(this.productoPrecio.getText());
                        Producto nuevoProducto = new Producto(
                                IdProd,
                                stock,
                                this.productoNombre.getText(),
                                this.rutaImagen.getText(),
                                precioProd
                        );

                        gest.modificarProducto(nuevoProducto);
                        JOptionPane.showMessageDialog(this, "<html><h3>Producto Insertado</h3></html>");
                        this.productoNombre.setText("");
                        this.productoId.setText("");
                        this.productoStock.setText("");
                        this.productoPrecio.setText("");
                        this.rutaImagen.setText("");

                    } else {

                        if (this.productoNombre.getText().isEmpty() == true) {
                            this.productoNombre.setBackground(Color.yellow);
                        } else {
                            this.productoNombre.setBackground(Color.white);
                        }
                        if (this.productoId.getText().isEmpty() == true) {
                            this.productoId.setBackground(Color.yellow);
                        } else {
                            this.productoId.setBackground(Color.white);
                        }
                        if (this.productoStock.getText().isEmpty() == true) {
                            this.productoStock.setBackground(Color.yellow);
                        } else {
                            this.productoStock.setBackground(Color.white);
                        }
                        if (this.productoPrecio.getText().isEmpty() == true) {
                            this.productoPrecio.setBackground(Color.yellow);
                        } else {
                            this.productoPrecio.setBackground(Color.white);
                        }
                        if (this.rutaImagen.getText().isEmpty() == true) {
                            this.rutaImagen.setBackground(Color.yellow);
                        } else {
                            this.rutaImagen.setBackground(Color.white);
                        }

                        JOptionPane.showMessageDialog(this, "<html><h3>Error al Modificar Producto, por favor,<br> revise los campos sin rellenar </h3></html>");

                    }
                    break;

                case 2:
                    if (this.productoId.getText().isEmpty() == false) {
                        Integer IdAdmin = Integer.parseInt(this.productoId.getText());
                        Producto ProductoBorrar = new Producto(IdAdmin);
                        {
                            gest.borrarProducto(ProductoBorrar);
                            JOptionPane.showMessageDialog(this, "<html><h3>Producto Eliminado</h3></html>");
                            this.productoNombre.setText("");
                            this.productoId.setText("");
                            this.productoStock.setText("");
                            this.productoPrecio.setText("");
                            this.rutaImagen.setText("");
                        }
                    } else {
                        if (this.productoId.getText().isEmpty() == true) {
                            this.productoId.setBackground(Color.yellow);
                        } else {
                            this.productoId.setBackground(Color.white);
                        }

                        JOptionPane.showMessageDialog(this, "<html><h3>Error al eliminar Usuario, por favor,<br> intrudzca un valor válido </h3></html>");

                    }
                    break;

                case 3:
                    if (this.productoId.getText().isEmpty() == false) {
                        Integer IdProd = Integer.parseInt(this.productoId.getText());

                        {
                            gest.buscarProducto(IdProd);
                            try {
                                this.cargarUnProducto();
                            } catch (SQLException | ClassNotFoundException ex) {
                                Logger.getLogger(AdminNuevo.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            this.productoNombre.setText("");
                            this.productoId.setText("");
                            this.productoStock.setText("");
                            this.productoPrecio.setText("");
                            this.rutaImagen.setText("");
                        }
                    } else {
                        if (this.productoId.getText().isEmpty() == true) {
                            this.productoId.setBackground(Color.yellow);
                        } else {
                            this.productoId.setBackground(Color.white);
                        }

                        JOptionPane.showMessageDialog(this, "<html><h3>Error al encontrar Producto, por favor,<br> intrudzca un valor válido </h3></html>");

                    }
                    break;
            }

        }

    }//GEN-LAST:event_jBOkActionPerformed

    private void btnBuscarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarImagenActionPerformed
        this.jFileChooser1.setVisible(true);
        this.jFileChooser1.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        FileNameExtensionFilter imgFilter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif");

        this.jFileChooser1.setFileFilter(imgFilter);

        int result = this.jFileChooser1.showOpenDialog(this);

        if (result != JFileChooser.CANCEL_OPTION) {

            File fileName = this.jFileChooser1.getSelectedFile();

            if ((fileName == null) || (fileName.getName().equals(""))) {
                this.rutaImagen.setText("...");
            } else {
                this.rutaImagen.setText(fileName.getAbsolutePath());
            }

        }
    }//GEN-LAST:event_btnBuscarImagenActionPerformed

    private void btnTPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTPVActionPerformed
        TPV tpv = new TPV(true);
        tpv.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTPVActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jRadioInsertarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioInsertarProductoActionPerformed
        switchProductos = 0;
        this.productoId.setEnabled(true);
        this.productoNombre.setEnabled(true);
        this.productoPrecio.setEnabled(true);
        this.productoStock.setEnabled(true);
    }//GEN-LAST:event_jRadioInsertarProductoActionPerformed

    private void jRadioModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioModificarProductoActionPerformed
        switchProductos = 1;
        this.productoId.setEnabled(true);
        this.productoNombre.setEnabled(true);
        this.productoPrecio.setEnabled(true);
        this.productoStock.setEnabled(true);
    }//GEN-LAST:event_jRadioModificarProductoActionPerformed

    private void jRadioEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEliminarProductoActionPerformed
        switchProductos = 2;
        this.productoId.setEnabled(true);
        this.productoNombre.setEnabled(false);
        this.productoPrecio.setEnabled(false);
        this.productoStock.setEnabled(false);
    }//GEN-LAST:event_jRadioEliminarProductoActionPerformed

    private void jRadioBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBuscarProductoActionPerformed
        switchProductos = 3;
        this.productoId.setEnabled(true);
        this.productoNombre.setEnabled(false);
        this.productoPrecio.setEnabled(false);
        this.productoStock.setEnabled(false);
    }//GEN-LAST:event_jRadioBuscarProductoActionPerformed

    private void btnInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformesActionPerformed
        try {
            Informes inf = new Informes();
            inf.setVisible(true);
            dispose();
        } catch (ClassNotFoundException | SQLException | JRException ex) {
            Logger.getLogger(AdminNuevo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInformesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminNuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminId;
    private javax.swing.JLabel AdminId1;
    private javax.swing.JPanel PanelProducto;
    private javax.swing.JPanel PanelUsuario;
    private javax.swing.JButton btnBuscarImagen;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnInformes;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnTPV;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton jBOk;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRInsertarUsuario;
    private javax.swing.JRadioButton jRadioBuscarProducto;
    private javax.swing.JRadioButton jRadioBuscarUsuario;
    private javax.swing.JRadioButton jRadioEliminarProducto;
    private javax.swing.JRadioButton jRadioEliminarUsuario;
    private javax.swing.JRadioButton jRadioInsertarProducto;
    private javax.swing.JRadioButton jRadioModificarProducto;
    private javax.swing.JRadioButton jRadioModificarUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField productoId;
    private javax.swing.JTextField productoNombre;
    private javax.swing.JTextField productoPrecio;
    private javax.swing.JTextField productoStock;
    private javax.swing.ButtonGroup rbProductos;
    private javax.swing.ButtonGroup rbUsuarios;
    private javax.swing.JList<String> resultadoBusqueda;
    private javax.swing.JTextField rutaImagen;
    private javax.swing.JTextField usuarioId;
    private javax.swing.JTextField usuarioNombre;
    private javax.swing.JTextField usuarioPass;
    // End of variables declaration//GEN-END:variables
}
