/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TPV.GUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
import org.jdatepicker.JDatePanel;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;
import tpv.DateLabelFormatter;

/**
 *
 * @author Jairo
 */
public class Informes extends javax.swing.JFrame {
    String inicio;
    String fin;
    JDatePickerImpl datePickerIni,datePickerFin;
    /**
     * Creates new form Informes
     *
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     * @throws net.sf.jasperreports.engine.JRException
     */
    public Informes() throws ClassNotFoundException, SQLException, JRException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        UtilDateModel modelIni = new UtilDateModel();
        modelIni.setDate(2021, 0, 1);
        modelIni.setSelected(true);

        Properties p1 = new Properties();
        p1.put("text.today", "Hoy");
        p1.put("text.month", "Mes");
        p1.put("text.year", "Año");
        JDatePanelImpl datePanel1 = new JDatePanelImpl(modelIni, p1);

        datePickerIni = new JDatePickerImpl(datePanel1, new DateLabelFormatter());
        fechaIni.add(datePickerIni,new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 100));
        
        //---------------------------------------------------
        
        UtilDateModel modelFin = new UtilDateModel();
        modelFin.setDate(2021, 0, 1);
        modelFin.setSelected(true);

        Properties p2 = new Properties();
        p2.put("text.today", "Hoy");
        p2.put("text.month", "Mes");
        p2.put("text.year", "Año");
        JDatePanelImpl datePanel2 = new JDatePanelImpl(modelFin, p2);

        datePickerFin = new JDatePickerImpl(datePanel2, new DateLabelFormatter());
      
        fechaFin.add(datePickerFin,new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 100));
        
    }

    Informes(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelReporte = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        informeVentasFecha = new javax.swing.JButton();
        fechaFin = new javax.swing.JPanel();
        fechaIni = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        informeVendedores = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        informeCompras = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cantidadStockProducto = new javax.swing.JTextField();
        botonVolverInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelReporte.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1041, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );

        PanelReporte.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informe de ventas por fecha"));

        jLabel1.setText("Fecha fin");

        jLabel2.setText("Fecha Inicio");

        informeVentasFecha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        informeVentasFecha.setText("Ventas");
        informeVentasFecha.setFocusTraversalPolicyProvider(true);
        informeVentasFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informeVentasFechaActionPerformed(evt);
            }
        });

        fechaFin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        fechaFin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fechaIni.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        fechaIni.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informeVentasFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(fechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(fechaIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(87, 87, 87)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(informeVentasFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(fechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(229, Short.MAX_VALUE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Informe venta por vendedor"));

        informeVendedores.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        informeVendedores.setText("Vendedores");
        informeVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informeVendedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informeVendedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(informeVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Informe de compras"));

        informeCompras.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        informeCompras.setText("Compras");
        informeCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informeComprasActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad Mínima");

        cantidadStockProducto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantidadStockProducto)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 79, Short.MAX_VALUE))
                    .addComponent(informeCompras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidadStockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(informeCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        botonVolverInfo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonVolverInfo.setText("Volver");
        botonVolverInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonVolverInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(PanelReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(botonVolverInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void informeVentasFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informeVentasFechaActionPerformed
        this.PanelReporte.removeAll();
        inicio = datePickerIni.getJFormattedTextField().getText();
        fin = datePickerFin.getJFormattedTextField().getText();
      
        JasperPrint jp1 = null;
        JRViewer viewer1 = null;
        String ficheroReporteVentasFecha = "reports\\informeVentasFechaNuevo.jrxml";

        HashMap<String, Object> parameterMap = new HashMap<String, Object>();

        Connection conexion;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sandwichdb", "root", "");

            JasperReport reporteCompilado2 = JasperCompileManager.compileReport(ficheroReporteVentasFecha);

            parameterMap.put("fechaInicio", inicio);
            parameterMap.put("fechaFin", fin);

            jp1 = JasperFillManager.fillReport(reporteCompilado2, parameterMap, conexion);

        } catch (ClassNotFoundException | SQLException | JRException ex) {
            System.out.println(ex);
        }
        viewer1 = new JRViewer(jp1);

        this.PanelReporte.add(viewer1);

        this.PanelReporte.revalidate();
    }//GEN-LAST:event_informeVentasFechaActionPerformed

    private void informeVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informeVendedoresActionPerformed

        this.PanelReporte.removeAll();
        JasperPrint jp2 = null;
        JRViewer viewer2 = null;
        String ficheroReporteVentasUsu = "reports\\informeVentasUsuarios.jrxml";

        HashMap<String, Object> parameterMap = new HashMap<String, Object>();

        Connection conexion;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sandwichdb", "root", "");

            JasperReport reporteCompilado1 = JasperCompileManager.compileReport(ficheroReporteVentasUsu);

            jp2 = JasperFillManager.fillReport(reporteCompilado1, parameterMap, conexion);

        } catch (ClassNotFoundException | SQLException | JRException ex) {
            System.out.println(ex);
        }
        viewer2 = new JRViewer(jp2);

        this.PanelReporte.add(viewer2);
        this.PanelReporte.revalidate();
    }//GEN-LAST:event_informeVendedoresActionPerformed

    private void informeComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informeComprasActionPerformed
        if (!cantidadStockProducto.getText().equals("")) {
            this.PanelReporte.removeAll();
        JasperPrint jp3 = null;
        JRViewer viewer = null;
        String ficheroReporteCompras = "reports\\Compras.jrxml";

        HashMap<String, Object> parameterMap = new HashMap<String, Object>();

        Connection conexion;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sandwichdb", "root", "");

            JasperReport reporteCompilado = JasperCompileManager.compileReport(ficheroReporteCompras);

            parameterMap.put("cantidadStock", Integer.parseInt(cantidadStockProducto.getText()));

            jp3 = JasperFillManager.fillReport(reporteCompilado, parameterMap, conexion);

        } catch (ClassNotFoundException | SQLException | JRException ex) {
            System.out.println(ex);
        }
        viewer = new JRViewer(jp3);

        this.PanelReporte.add(viewer);

        this.PanelReporte.revalidate();
        }else{
            JOptionPane.showMessageDialog(this, "<html><h2>Introduce un valor para el stock "
                    + "</h2><br></html>" , 
                    "Error de verificación", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_informeComprasActionPerformed

    private void botonVolverInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverInfoActionPerformed
        AdminNuevo admin = new AdminNuevo();
        admin.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonVolverInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Informes().setVisible(true);
                } catch (ClassNotFoundException | SQLException | JRException ex) {
                    Logger.getLogger(Informes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelReporte;
    private javax.swing.JButton botonVolverInfo;
    private javax.swing.JTextField cantidadStockProducto;
    private javax.swing.JPanel fechaFin;
    private javax.swing.JPanel fechaIni;
    private javax.swing.JButton informeCompras;
    private javax.swing.JButton informeVendedores;
    private javax.swing.JButton informeVentasFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
