/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TPV.GUI;

import TPV.Clases.*;
import java.sql.SQLException;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 * @author Fran
 * @author Jairo
 */
public class TPV extends javax.swing.JFrame {

    GestionBDRegistro gest;
    String numProductos;
    boolean frios,calientes,bebidas;

    public int getUsuarioRegistrado() {
        return usuarioRegistrado;
    }

    public void setUsuarioRegistrado(int usuarioRegistrado) {
        this.usuarioRegistrado = usuarioRegistrado;
    }
    int usuarioRegistrado;

    public TPV(boolean admin) {
        initComponents();
        this.setLocationRelativeTo(null);

        this.setResizable(false);
        this.btnAdministracion.setVisible(admin);
        this.Ticket.removeAll();
        this.Ticket.setModel(model);
        this.PaneProductosBebidas.setVisible(false);
        this.PaneProductosFrios.setVisible(false);
        this.PaneProductosCalientes.setVisible(false);

        frios = false;
        calientes = false;
        bebidas = false; 
        numProductos = "";
        
        gest = new GestionBDRegistro("root", "", "sandwichDb", "localhost");

    }

    DefaultListModel model = new DefaultListModel();
    ArrayList<String> cuenta = new ArrayList<String>();

    /**
     * Creates new form TPV
     */
    public TPV() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Ticket = new javax.swing.JList<>();
        panelBotonesControl = new javax.swing.JPanel();
        botonCobrar = new javax.swing.JButton();
        botonFactura = new javax.swing.JButton();
        botonBorrarUno = new javax.swing.JButton();
        botonBorrarTodo = new javax.swing.JButton();
        cerrarAplicacion = new javax.swing.JButton();
        Total = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        totalPrecioVenta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        totalIva = new javax.swing.JTextField();
        Logo = new javax.swing.JLabel();
        LayeredBotonera = new javax.swing.JLayeredPane();
        PaneProductosIndex = new javax.swing.JPanel();
        botonBebidas = new javax.swing.JButton();
        botonCalientes = new javax.swing.JButton();
        botonFrios = new javax.swing.JButton();
        PaneProductosCalientes = new javax.swing.JPanel();
        calienteJamonQueso = new javax.swing.JLabel();
        calienteSalmon = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        calienteSolomillo = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        calienteJamonQueso1 = new javax.swing.JLabel();
        calienteSalmon1 = new javax.swing.JLabel();
        calienteSolomillo1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        PaneProductosFrios = new javax.swing.JPanel();
        friosQuesoTom = new javax.swing.JLabel();
        friosSerrano = new javax.swing.JLabel();
        friosVegetal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        friosBaconHuevo = new javax.swing.JLabel();
        friosPavoManzana = new javax.swing.JLabel();
        friosQuesoTom6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        friosAzulRucula = new javax.swing.JLabel();
        friosCurry = new javax.swing.JLabel();
        friosQuesoTom7 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        atras1 = new javax.swing.JButton();
        PaneProductosBebidas = new javax.swing.JPanel();
        bebidaCocaCola = new javax.swing.JLabel();
        bebidaNaranja = new javax.swing.JLabel();
        bebidaCerveza = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        bebidaLimon = new javax.swing.JLabel();
        atras2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JButton();
        btnAdministracion = new javax.swing.JButton();
        PanelNumeros = new javax.swing.JPanel();
        calc0 = new javax.swing.JButton();
        calc2 = new javax.swing.JButton();
        calc6 = new javax.swing.JButton();
        calc1 = new javax.swing.JButton();
        calc7 = new javax.swing.JButton();
        calc4 = new javax.swing.JButton();
        calc5 = new javax.swing.JButton();
        calc8 = new javax.swing.JButton();
        calc3 = new javax.swing.JButton();
        calc9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Ticket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Ticket.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jScrollPane1.setViewportView(Ticket);

        panelBotonesControl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonCobrar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        botonCobrar.setText("Cobrar");
        botonCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCobrarActionPerformed(evt);
            }
        });

        botonFactura.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        botonFactura.setText("Facturar");
        botonFactura.setEnabled(false);

        botonBorrarUno.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        botonBorrarUno.setText("Borrar Uno");
        botonBorrarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarUnoActionPerformed(evt);
            }
        });

        botonBorrarTodo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        botonBorrarTodo.setText("Borrar Todo");
        botonBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarTodoActionPerformed(evt);
            }
        });

        cerrarAplicacion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cerrarAplicacion.setText("Cerrar");
        cerrarAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarAplicacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesControlLayout = new javax.swing.GroupLayout(panelBotonesControl);
        panelBotonesControl.setLayout(panelBotonesControlLayout);
        panelBotonesControlLayout.setHorizontalGroup(
            panelBotonesControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesControlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBotonesControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonCobrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesControlLayout.createSequentialGroup()
                        .addGroup(panelBotonesControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonBorrarUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBotonesControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cerrarAplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonBorrarTodo, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelBotonesControlLayout.setVerticalGroup(
            panelBotonesControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cerrarAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBotonesControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBorrarUno, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Total:");

        totalPrecioVenta.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        totalPrecioVenta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalPrecioVenta.setText("0.0");
        totalPrecioVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        totalPrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPrecioVentaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Iva ");

        totalIva.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        totalIva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalIva.setText("0.0");
        totalIva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout TotalLayout = new javax.swing.GroupLayout(Total);
        Total.setLayout(TotalLayout);
        TotalLayout.setHorizontalGroup(
            TotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalPrecioVenta)
                    .addComponent(totalIva, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        TotalLayout.setVerticalGroup(
            TotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(TotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Logo.setBackground(new java.awt.Color(255, 255, 255));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenesTpv/logoMini.jpg"))); // NOI18N
        Logo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PaneProductosIndex.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonBebidas.setText("Bebidas");
        botonBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBebidasActionPerformed(evt);
            }
        });

        botonCalientes.setText("Calientes");
        botonCalientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalientesActionPerformed(evt);
            }
        });

        botonFrios.setText("Frios");
        botonFrios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PaneProductosIndexLayout = new javax.swing.GroupLayout(PaneProductosIndex);
        PaneProductosIndex.setLayout(PaneProductosIndexLayout);
        PaneProductosIndexLayout.setHorizontalGroup(
            PaneProductosIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneProductosIndexLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(botonFrios, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(botonCalientes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(botonBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        PaneProductosIndexLayout.setVerticalGroup(
            PaneProductosIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneProductosIndexLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaneProductosIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCalientes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonFrios, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(756, Short.MAX_VALUE))
        );

        PaneProductosCalientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        calienteJamonQueso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calienteJamonQueso.setText("Jamon y queso");
        calienteJamonQueso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calienteJamonQueso.setName("8"); // NOI18N
        calienteJamonQueso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calienteJamonQuesoMouseClicked(evt);
            }
        });

        calienteSalmon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calienteSalmon.setText("Salmon");
        calienteSalmon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calienteSalmon.setName("9"); // NOI18N
        calienteSalmon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calienteSalmonMouseClicked(evt);
            }
        });

        jLabel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        calienteSolomillo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calienteSolomillo.setText("solomillo");
        calienteSolomillo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calienteSolomillo.setName("10"); // NOI18N
        calienteSolomillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calienteSolomilloMouseClicked(evt);
            }
        });

        atras.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        atras.setText("Atrás");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        calienteJamonQueso1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        calienteSalmon1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        calienteSolomillo1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel32.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout PaneProductosCalientesLayout = new javax.swing.GroupLayout(PaneProductosCalientes);
        PaneProductosCalientes.setLayout(PaneProductosCalientesLayout);
        PaneProductosCalientesLayout.setHorizontalGroup(
            PaneProductosCalientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneProductosCalientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaneProductosCalientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaneProductosCalientesLayout.createSequentialGroup()
                        .addComponent(calienteJamonQueso1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calienteSalmon1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calienteSolomillo1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PaneProductosCalientesLayout.createSequentialGroup()
                        .addComponent(calienteJamonQueso, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calienteSalmon, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calienteSolomillo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneProductosCalientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PaneProductosCalientesLayout.setVerticalGroup(
            PaneProductosCalientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneProductosCalientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaneProductosCalientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calienteSolomillo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calienteJamonQueso, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calienteSalmon, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaneProductosCalientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calienteSolomillo1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calienteJamonQueso1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calienteSalmon1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 486, Short.MAX_VALUE)
                .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PaneProductosFrios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        friosQuesoTom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        friosQuesoTom.setText("Queso Tomate");
        friosQuesoTom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        friosQuesoTom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        friosQuesoTom.setName("3"); // NOI18N
        friosQuesoTom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friosQuesoTomMouseClicked(evt);
            }
        });

        friosSerrano.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        friosSerrano.setText("Serrano");
        friosSerrano.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        friosSerrano.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        friosSerrano.setName("1"); // NOI18N
        friosSerrano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friosSerranoMouseClicked(evt);
            }
        });

        friosVegetal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        friosVegetal.setText("Vegetal");
        friosVegetal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        friosVegetal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        friosVegetal.setName("2"); // NOI18N
        friosVegetal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friosVegetalMouseClicked(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        friosBaconHuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        friosBaconHuevo.setText("Bacon Huevo");
        friosBaconHuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        friosBaconHuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        friosBaconHuevo.setName("4"); // NOI18N
        friosBaconHuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friosBaconHuevoMouseClicked(evt);
            }
        });

        friosPavoManzana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        friosPavoManzana.setText("Pavo Manzana");
        friosPavoManzana.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        friosPavoManzana.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        friosPavoManzana.setName("5"); // NOI18N
        friosPavoManzana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friosPavoManzanaMouseClicked(evt);
            }
        });

        friosQuesoTom6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        friosQuesoTom6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        friosQuesoTom6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        friosAzulRucula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        friosAzulRucula.setText("Azul y Rúcula");
        friosAzulRucula.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        friosAzulRucula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        friosAzulRucula.setName("6"); // NOI18N
        friosAzulRucula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friosAzulRuculaMouseClicked(evt);
            }
        });

        friosCurry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        friosCurry.setText("Pollo Curry");
        friosCurry.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        friosCurry.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        friosCurry.setName("7"); // NOI18N
        friosCurry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friosCurryMouseClicked(evt);
            }
        });

        friosQuesoTom7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        friosQuesoTom7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        friosQuesoTom7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        atras1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        atras1.setText("Atrás");
        atras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atras1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PaneProductosFriosLayout = new javax.swing.GroupLayout(PaneProductosFrios);
        PaneProductosFrios.setLayout(PaneProductosFriosLayout);
        PaneProductosFriosLayout.setHorizontalGroup(
            PaneProductosFriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneProductosFriosLayout.createSequentialGroup()
                .addGroup(PaneProductosFriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaneProductosFriosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PaneProductosFriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PaneProductosFriosLayout.createSequentialGroup()
                                .addComponent(friosSerrano, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(friosVegetal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(friosQuesoTom, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PaneProductosFriosLayout.createSequentialGroup()
                                .addComponent(friosBaconHuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(friosPavoManzana, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(friosQuesoTom6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PaneProductosFriosLayout.createSequentialGroup()
                                .addComponent(friosAzulRucula, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(friosCurry, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(friosQuesoTom7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneProductosFriosLayout.createSequentialGroup()
                        .addGap(523, 523, 523)
                        .addComponent(atras1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PaneProductosFriosLayout.setVerticalGroup(
            PaneProductosFriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneProductosFriosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaneProductosFriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(friosQuesoTom, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(friosSerrano, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(friosVegetal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaneProductosFriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(friosQuesoTom6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(friosBaconHuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(friosPavoManzana, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaneProductosFriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(friosQuesoTom7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(friosAzulRucula, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(friosCurry, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(376, 376, 376)
                .addComponent(atras1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        friosSerrano.getAccessibleContext().setAccessibleDescription("");

        PaneProductosBebidas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bebidaCocaCola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bebidaCocaCola.setText("Coca Cola");
        bebidaCocaCola.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bebidaCocaCola.setName("11"); // NOI18N
        bebidaCocaCola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bebidaCocaColaMouseClicked(evt);
            }
        });

        bebidaNaranja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bebidaNaranja.setText("Fanta Naranja");
        bebidaNaranja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bebidaNaranja.setName("12"); // NOI18N
        bebidaNaranja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bebidaNaranjaMouseClicked(evt);
            }
        });

        bebidaCerveza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bebidaCerveza.setText("Cerveza");
        bebidaCerveza.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bebidaCerveza.setName("14"); // NOI18N
        bebidaCerveza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bebidaCervezaMouseClicked(evt);
            }
        });

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bebidaLimon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bebidaLimon.setText("Fanta Limon");
        bebidaLimon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bebidaLimon.setName("13"); // NOI18N
        bebidaLimon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bebidaLimonMouseClicked(evt);
            }
        });

        atras2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        atras2.setText("Atrás");
        atras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atras2ActionPerformed(evt);
            }
        });

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout PaneProductosBebidasLayout = new javax.swing.GroupLayout(PaneProductosBebidas);
        PaneProductosBebidas.setLayout(PaneProductosBebidasLayout);
        PaneProductosBebidasLayout.setHorizontalGroup(
            PaneProductosBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneProductosBebidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaneProductosBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bebidaCocaCola, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PaneProductosBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bebidaNaranja, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PaneProductosBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bebidaLimon, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PaneProductosBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bebidaCerveza, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(PaneProductosBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneProductosBebidasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(atras2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PaneProductosBebidasLayout.setVerticalGroup(
            PaneProductosBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneProductosBebidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaneProductosBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bebidaLimon, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bebidaCocaCola, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bebidaNaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bebidaCerveza, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaneProductosBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 510, Short.MAX_VALUE)
                .addComponent(atras2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        LayeredBotonera.setLayer(PaneProductosIndex, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredBotonera.setLayer(PaneProductosCalientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredBotonera.setLayer(PaneProductosFrios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredBotonera.setLayer(PaneProductosBebidas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayeredBotoneraLayout = new javax.swing.GroupLayout(LayeredBotonera);
        LayeredBotonera.setLayout(LayeredBotoneraLayout);
        LayeredBotoneraLayout.setHorizontalGroup(
            LayeredBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredBotoneraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaneProductosIndex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(LayeredBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LayeredBotoneraLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PaneProductosCalientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(LayeredBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LayeredBotoneraLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PaneProductosFrios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(LayeredBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LayeredBotoneraLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PaneProductosBebidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        LayeredBotoneraLayout.setVerticalGroup(
            LayeredBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredBotoneraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaneProductosIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LayeredBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LayeredBotoneraLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PaneProductosCalientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(9, Short.MAX_VALUE)))
            .addGroup(LayeredBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LayeredBotoneraLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PaneProductosFrios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(9, Short.MAX_VALUE)))
            .addGroup(LayeredBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LayeredBotoneraLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PaneProductosBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btnUsuario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnUsuario.setText("Usuario");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        btnAdministracion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnAdministracion.setText("Admin");
        btnAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministracionActionPerformed(evt);
            }
        });

        PanelNumeros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        calc0.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        calc0.setText("0");
        calc0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc0ActionPerformed(evt);
            }
        });

        calc2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        calc2.setText("2");
        calc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc2ActionPerformed(evt);
            }
        });

        calc6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        calc6.setText("6");
        calc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc6ActionPerformed(evt);
            }
        });

        calc1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        calc1.setText("1");
        calc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc1ActionPerformed(evt);
            }
        });

        calc7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        calc7.setText("7");
        calc7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc7ActionPerformed(evt);
            }
        });

        calc4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        calc4.setText("4");
        calc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc4ActionPerformed(evt);
            }
        });

        calc5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        calc5.setText("5");
        calc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc5ActionPerformed(evt);
            }
        });

        calc8.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        calc8.setText("8");
        calc8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc8ActionPerformed(evt);
            }
        });

        calc3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        calc3.setText(" 3");
        calc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc3ActionPerformed(evt);
            }
        });

        calc9.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        calc9.setText("9");
        calc9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNumerosLayout = new javax.swing.GroupLayout(PanelNumeros);
        PanelNumeros.setLayout(PanelNumerosLayout);
        PanelNumerosLayout.setHorizontalGroup(
            PanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNumerosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(calc0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelNumerosLayout.createSequentialGroup()
                        .addGroup(PanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelNumerosLayout.createSequentialGroup()
                                .addComponent(calc7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(calc8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelNumerosLayout.createSequentialGroup()
                                .addComponent(calc4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calc5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelNumerosLayout.createSequentialGroup()
                                .addComponent(calc1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calc2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calc6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calc3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calc9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNumerosLayout.setVerticalGroup(
            PanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNumerosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calc1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calc2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calc3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(calc4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calc5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calc6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calc8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(calc7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(calc9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calc0, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnAdministracion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdministracion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Logo))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LayeredBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBotonesControl, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelBotonesControl, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LayeredBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Logo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPrecioVentaActionPerformed

    }//GEN-LAST:event_totalPrecioVentaActionPerformed

    private void calc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc4ActionPerformed
        numProductos = numProductos + "4";
    }//GEN-LAST:event_calc4ActionPerformed

    private void calc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc2ActionPerformed
        numProductos = numProductos + "2";
    }//GEN-LAST:event_calc2ActionPerformed

    private void calc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc3ActionPerformed
        numProductos = numProductos + "3";
    }//GEN-LAST:event_calc3ActionPerformed

    private void calc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc5ActionPerformed
        numProductos = numProductos + "5";
    }//GEN-LAST:event_calc5ActionPerformed

    private void calc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc6ActionPerformed
        numProductos = numProductos + "6";
    }//GEN-LAST:event_calc6ActionPerformed

    private void calc7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc7ActionPerformed
        numProductos = numProductos + "7";
    }//GEN-LAST:event_calc7ActionPerformed

    private void calc8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc8ActionPerformed
        numProductos = numProductos + "8";
    }//GEN-LAST:event_calc8ActionPerformed

    private void calc9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc9ActionPerformed
        numProductos = numProductos + "9";
    }//GEN-LAST:event_calc9ActionPerformed

    private void calc0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc0ActionPerformed
        numProductos = numProductos + "0";
    }//GEN-LAST:event_calc0ActionPerformed

    private void cerrarAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarAplicacionActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_cerrarAplicacionActionPerformed

    private void botonCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCobrarActionPerformed


        RegistroVenta rv = new RegistroVenta();
        float precioTotal = Float.parseFloat(this.totalPrecioVenta.getText());
        rv.setPrecioTotal(precioTotal);

        gest.insertarVenta(rv);
        
        VentaProducto vp = new VentaProducto();
        vp.setVendedor(usuarioRegistrado);
;
        for (int i = 0; i < model.size(); i++) {
            String[] parts = String.valueOf(model.get(i)).split(" x");
            vp.setIdVenta(gest.recuperaTicket());
            vp.setIdProducto(gest.recuperaIdProducto(parts[0]));
            vp.setCantidad(Integer.parseInt(parts[1]));
            gest.insertarVP(vp);
        }
        

        model.removeAllElements();
        this.totalIva.setText("0.0");
        this.totalPrecioVenta.setText("0.0");
        numProductos = "";
    }//GEN-LAST:event_botonCobrarActionPerformed

    private void botonCalientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalientesActionPerformed
        this.PaneProductosIndex.setVisible(false);
        this.PaneProductosFrios.setVisible(false);
        this.PaneProductosCalientes.setVisible(true);

        ArrayList labelsProductos = new ArrayList();
        labelsProductos.add(this.calienteJamonQueso);
        labelsProductos.add(this.calienteSalmon);
        labelsProductos.add(this.calienteSolomillo);
        if(!calientes){
            asignaImagen(labelsProductos);
            calientes = true;
        }
        
    }//GEN-LAST:event_botonCalientesActionPerformed

    private void botonFriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFriosActionPerformed
        this.PaneProductosIndex.setVisible(false);
        this.PaneProductosCalientes.setVisible(false);
        this.PaneProductosFrios.setVisible(true);
        this.PaneProductosBebidas.setVisible(false);
        
        if(!frios){
            ArrayList labelsProductos = new ArrayList();
            labelsProductos.add(this.friosSerrano);
            labelsProductos.add(this.friosVegetal);
            labelsProductos.add(this.friosQuesoTom);
            labelsProductos.add(this.friosBaconHuevo);
            labelsProductos.add(this.friosPavoManzana);
            labelsProductos.add(this.friosAzulRucula);
            labelsProductos.add(this.friosCurry);
        
            asignaImagen(labelsProductos);
            frios = true;
        }
    }//GEN-LAST:event_botonFriosActionPerformed

    private void botonBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBebidasActionPerformed
        this.PaneProductosIndex.setVisible(false);
        this.PaneProductosCalientes.setVisible(false);
        this.PaneProductosFrios.setVisible(false);
        this.PaneProductosBebidas.setVisible(true);

        ArrayList labelsProductos = new ArrayList();

        labelsProductos.add(this.bebidaCocaCola);
        labelsProductos.add(this.bebidaNaranja);
        labelsProductos.add(this.bebidaLimon);
        labelsProductos.add(this.bebidaCerveza);

        if(!bebidas){
            asignaImagen(labelsProductos);
            bebidas = true;
        }
    }//GEN-LAST:event_botonBebidasActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        this.PaneProductosIndex.setVisible(true);
        this.PaneProductosCalientes.setVisible(false);
        this.PaneProductosFrios.setVisible(false);
        this.PaneProductosBebidas.setVisible(false);
    }//GEN-LAST:event_atrasActionPerformed

    private void atras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atras1ActionPerformed
        this.PaneProductosIndex.setVisible(true);
        this.PaneProductosCalientes.setVisible(false);
        this.PaneProductosFrios.setVisible(false);
        this.PaneProductosBebidas.setVisible(false);
    }//GEN-LAST:event_atras1ActionPerformed

    private void atras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atras2ActionPerformed

        this.PaneProductosIndex.setVisible(true);
        this.PaneProductosCalientes.setVisible(false);
        this.PaneProductosFrios.setVisible(false);
        this.PaneProductosBebidas.setVisible(false);
    }//GEN-LAST:event_atras2ActionPerformed

    private void botonBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarTodoActionPerformed

        model.removeAllElements();
        this.totalIva.setText("0.0");
        this.totalPrecioVenta.setText("0.0");
        numProductos = "";
    }//GEN-LAST:event_botonBorrarTodoActionPerformed

    private void botonBorrarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarUnoActionPerformed
        try {
            // parts[0] contendra el nombre del producto
            //parts[1] contendrá el numero de los productos especificos pedido
            String[] parts = Ticket.getSelectedValue().split(" x");
            int numPedido = Integer.parseInt(parts[1]);
            
            model.remove(Ticket.getSelectedIndex());

            restaCuenta(gest.buscarProducto(parts[0]),numPedido);
            restaIva(gest.buscarProducto(parts[0]), numPedido);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "selecciona un elemento del ticket");
        }
    }//GEN-LAST:event_botonBorrarUnoActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        VentanaLogin vl = new VentanaLogin();
        vl.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministracionActionPerformed
        AdminNuevo admin = new AdminNuevo();
        admin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAdministracionActionPerformed

    private void friosSerranoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friosSerranoMouseClicked
        int idProducto = Integer.parseInt(this.friosSerrano.getName());
        Producto p = gest.buscarProducto(idProducto);

        if (!compruebaCuenta(p.getNombre())) {
            if(numProductos.equals("")) numProductos = "1";
            cuenta.add(p.getNombre() +" x"+numProductos);
        }
        
        for (int i = 0; i < cuenta.size(); i++) {

            model.addElement(cuenta.get(i));
            cuenta.remove(i);
        }
        sumaIva(p);
        sumaCuenta(p);
        numProductos = "";
    }//GEN-LAST:event_friosSerranoMouseClicked

    private void friosVegetalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friosVegetalMouseClicked
        
        int idProducto = Integer.parseInt(this.friosVegetal.getName());
        Producto p = gest.buscarProducto(idProducto);
        
        if (!compruebaCuenta(p.getNombre())) {
            if(numProductos.equals("")) numProductos = "1";
            cuenta.add(p.getNombre() +" x"+numProductos);
        }
        
        for (int i = 0; i < cuenta.size(); i++) {

            model.addElement(cuenta.get(i));
            cuenta.remove(i);
        }
        sumaIva(p);
        sumaCuenta(p);
        
    }//GEN-LAST:event_friosVegetalMouseClicked

    private void friosQuesoTomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friosQuesoTomMouseClicked
        int idProducto = Integer.parseInt(this.friosQuesoTom.getName());
        Producto p = gest.buscarProducto(idProducto);
        
        if (!compruebaCuenta(p.getNombre())) {
            if(numProductos.equals("")) numProductos = "1";
            cuenta.add(p.getNombre() +" x"+numProductos);
        }
        
        for (int i = 0; i < cuenta.size(); i++) {

            model.addElement(cuenta.get(i));
            cuenta.remove(i);
        }
        sumaIva(p);
        sumaCuenta(p);

    }//GEN-LAST:event_friosQuesoTomMouseClicked

    private void friosBaconHuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friosBaconHuevoMouseClicked
        int idProducto = Integer.parseInt(this.friosBaconHuevo.getName());
        Producto p = gest.buscarProducto(idProducto);

        if (!compruebaCuenta(p.getNombre())) {
            if(numProductos.equals("")) numProductos = "1";
            cuenta.add(p.getNombre() +" x"+numProductos);
        }
        
        for (int i = 0; i < cuenta.size(); i++) {

            model.addElement(cuenta.get(i));
            cuenta.remove(i);
        }
        sumaIva(p);
        sumaCuenta(p);
    }//GEN-LAST:event_friosBaconHuevoMouseClicked

    private void friosPavoManzanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friosPavoManzanaMouseClicked
        int idProducto = Integer.parseInt(this.friosPavoManzana.getName());
        Producto p = gest.buscarProducto(idProducto);

        if (!compruebaCuenta(p.getNombre())) {
            if(numProductos.equals("")) numProductos = "1";
            cuenta.add(p.getNombre() +" x"+numProductos);
        }
        
        for (int i = 0; i < cuenta.size(); i++) {

            model.addElement(cuenta.get(i));
            cuenta.remove(i);
        }
        sumaIva(p);
        sumaCuenta(p);
    }//GEN-LAST:event_friosPavoManzanaMouseClicked

    private void friosAzulRuculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friosAzulRuculaMouseClicked
        int idProducto = Integer.parseInt(this.friosAzulRucula.getName());
        Producto p = gest.buscarProducto(idProducto);

        if (!compruebaCuenta(p.getNombre())) {
            if(numProductos.equals("")) numProductos = "1";
            cuenta.add(p.getNombre() +" x"+numProductos);
        }
        
        for (int i = 0; i < cuenta.size(); i++) {

            model.addElement(cuenta.get(i));
            cuenta.remove(i);
        }
        sumaIva(p);
        sumaCuenta(p);
    }//GEN-LAST:event_friosAzulRuculaMouseClicked

    private void friosCurryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friosCurryMouseClicked
        int idProducto = Integer.parseInt(this.friosCurry.getName());
        Producto p = gest.buscarProducto(idProducto);

        if (!compruebaCuenta(p.getNombre())) {
            if(numProductos.equals("")) numProductos = "1";
            cuenta.add(p.getNombre() +" x"+numProductos);
        }
        
        for (int i = 0; i < cuenta.size(); i++) {

            model.addElement(cuenta.get(i));
            cuenta.remove(i);
        }
        sumaIva(p);
        sumaCuenta(p);
    }//GEN-LAST:event_friosCurryMouseClicked

    private void calienteJamonQuesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calienteJamonQuesoMouseClicked

        int idProducto = Integer.parseInt(this.calienteJamonQueso.getName());
        Producto p = gest.buscarProducto(idProducto);

        if (!compruebaCuenta(p.getNombre())) {
            if(numProductos.equals("")) numProductos = "1";
            cuenta.add(p.getNombre() +" x"+numProductos);
        }
        
        for (int i = 0; i < cuenta.size(); i++) {

            model.addElement(cuenta.get(i));
            cuenta.remove(i);
        }
        sumaIva(p);
        sumaCuenta(p);

    }//GEN-LAST:event_calienteJamonQuesoMouseClicked

    private void calienteSalmonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calienteSalmonMouseClicked
        int idProducto = Integer.parseInt(this.calienteSalmon.getName());
        Producto p = gest.buscarProducto(idProducto);

        if (!compruebaCuenta(p.getNombre())) {
            if(numProductos.equals("")) numProductos = "1";
            cuenta.add(p.getNombre() +" x"+numProductos);
        }
        
        for (int i = 0; i < cuenta.size(); i++) {

            model.addElement(cuenta.get(i));
            cuenta.remove(i);
        }
        sumaIva(p);
        sumaCuenta(p);
    }//GEN-LAST:event_calienteSalmonMouseClicked

    private void calienteSolomilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calienteSolomilloMouseClicked
        int idProducto = Integer.parseInt(this.calienteSolomillo.getName());
        Producto p = gest.buscarProducto(idProducto);

        if (!compruebaCuenta(p.getNombre())) {
            if(numProductos.equals("")) numProductos = "1";
            cuenta.add(p.getNombre() +" x"+numProductos);
        }
        
        for (int i = 0; i < cuenta.size(); i++) {

            model.addElement(cuenta.get(i));
            cuenta.remove(i);
        }
        sumaIva(p);
        sumaCuenta(p);

    }//GEN-LAST:event_calienteSolomilloMouseClicked

    private void bebidaCocaColaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bebidaCocaColaMouseClicked
        int idProducto = Integer.parseInt(this.bebidaCocaCola.getName());
        Producto p = gest.buscarProducto(idProducto);

        if (!compruebaCuenta(p.getNombre())) {
            if(numProductos.equals("")) numProductos = "1";
            cuenta.add(p.getNombre() +" x"+numProductos);
        }
        
        for (int i = 0; i < cuenta.size(); i++) {

            model.addElement(cuenta.get(i));
            cuenta.remove(i);
        }
        sumaIva(p);
        sumaCuenta(p);
    }//GEN-LAST:event_bebidaCocaColaMouseClicked

    private void bebidaNaranjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bebidaNaranjaMouseClicked
        int idProducto = Integer.parseInt(this.bebidaNaranja.getName());
        Producto p = gest.buscarProducto(idProducto);

        if (!compruebaCuenta(p.getNombre())) {
            if(numProductos.equals("")) numProductos = "1";
            cuenta.add(p.getNombre() +" x"+numProductos);
        }
        
        for (int i = 0; i < cuenta.size(); i++) {

            model.addElement(cuenta.get(i));
            cuenta.remove(i);
        }
        sumaIva(p);
        sumaCuenta(p);
    }//GEN-LAST:event_bebidaNaranjaMouseClicked

    private void bebidaLimonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bebidaLimonMouseClicked
        int idProducto = Integer.parseInt(this.bebidaLimon.getName());
        Producto p = gest.buscarProducto(idProducto);

        if (!compruebaCuenta(p.getNombre())) {
            if(numProductos.equals("")) numProductos = "1";
            cuenta.add(p.getNombre() +" x"+numProductos);
        }
        
        for (int i = 0; i < cuenta.size(); i++) {

            model.addElement(cuenta.get(i));
            cuenta.remove(i);
        }
        sumaIva(p);
        sumaCuenta(p);
    }//GEN-LAST:event_bebidaLimonMouseClicked

    private void bebidaCervezaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bebidaCervezaMouseClicked
        int idProducto = Integer.parseInt(this.bebidaCerveza.getName());
        Producto p = gest.buscarProducto(idProducto);
        
        if (!compruebaCuenta(p.getNombre())) {
            if(numProductos.equals("")) numProductos = "1";
            cuenta.add(p.getNombre() +" x"+numProductos);
        }
        
        for (int i = 0; i < cuenta.size(); i++) {

            model.addElement(cuenta.get(i));
            cuenta.remove(i);
        }
        sumaIva(p);
        sumaCuenta(p);
    }//GEN-LAST:event_bebidaCervezaMouseClicked

    private void calc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc1ActionPerformed
        numProductos = numProductos + "1";
    }//GEN-LAST:event_calc1ActionPerformed

    /**
     * devuelve el numero de un solo producto pedido en una misma cuenta
     * @return 
     */
    private int recuperaNumProductos(){
        int resultado;
        if(numProductos == "") resultado = 1;
        else resultado = Integer.parseInt(numProductos);
        
        return resultado;
    }
    
    /**
     * Suma el precio del nuevo producto añadido a la cuenta actual
     *
     * @param p Producto que se añade a la cuenta
     */
    private void sumaCuenta(Producto p) {
        String cuentaTxt;       

        Float cuentaActual = Float.parseFloat(this.totalPrecioVenta.getText());
        Float precioProducto = (p.getPrecio() + p.getIva())*recuperaNumProductos();

        cuentaActual = cuentaActual + precioProducto;
        cuentaTxt = String.valueOf(cuentaActual);

        this.totalPrecioVenta.setText(cuentaTxt);
        numProductos = "";

    }

    /**
     * Resta de la cuenta total el producto eliminado del ticket
     *
     * @param p producto que se ha borrado de la lista
     */
    private void restaCuenta(Producto p,int numPedido) {
        String cuentaTxt;
        Float cuentaActual = Float.parseFloat(this.totalPrecioVenta.getText());
        Float precioProducto = (p.getPrecio() + p.getIva()) * numPedido;

        cuentaActual = cuentaActual - precioProducto;
        if (cuentaActual < 0) {
            cuentaActual = (float) 0;
        }

        cuentaTxt = String.valueOf(cuentaActual);

        this.totalPrecioVenta.setText(cuentaTxt);
    }

    /**
     * Calcula el Iva de los productos y lo va añadiendo al ticket
     *
     * @param p Producto al que se le va a calcular el IVA
     * @return devuelve un producto con el iva ya incluido
     */
    private void sumaIva(Producto p) {
        String ivaTxt;
        float ivaActual = Float.parseFloat(this.totalIva.getText());
        float ivaProducto = p.getIva() * recuperaNumProductos();

        ivaActual = ivaActual + ivaProducto;
        ivaTxt = String.valueOf(ivaActual);

        this.totalIva.setText(ivaTxt);

    }
    
    private void restaIva(Producto p, int numPedido) {
        String ivaTxt;
        float ivaActual = Float.parseFloat(this.totalIva.getText());
        float ivaProducto = p.getIva()*numPedido;

        ivaActual = ivaActual - ivaProducto;
        if (ivaActual < 0) {
            ivaActual = (float) 0;
        }

        ivaTxt = String.valueOf(ivaActual);

        this.totalIva.setText(ivaTxt);
    }

    private void asignaImagen(ArrayList productos) {
        Producto p;
        for (int i = 0; i < productos.size(); i++) {

            JLabel labelP = (JLabel) productos.get(i);
            p = gest.buscarProducto(labelP.getText());
            labelP.setIcon(p.getIcon());
            labelP.setText("");
        }
    }

    /**
     * Comprueba si el producto que se va a añadir se encuentra en la cuenta ya
     * @param nombreProducto nombre del producto que se quiere comprobar
     * @return 
     */
   private boolean compruebaCuenta(String nombreProducto){
        boolean resultado = false;
        ListModel productos = Ticket.getModel();
        String producto;
                
        for (int i = 0; i < productos.getSize(); i++) {
          producto = productos.getElementAt(i).toString().split(" x")[0];
            if (producto.equals(nombreProducto)) {
                resultado = true;
                sumaProducto(i);
            }
       }
        
        return resultado;
    }
    
   /**
    * Cuando el producto ya se encuentre en el ticket añadirá 1 al total
    * @param indice
    * @param nombreProducto 
    */
   private void sumaProducto(int indice){
       String actualizacion; 
       String productoActual = (String) model.getElementAt(indice);
       int totalActual = Integer.parseInt(productoActual.split(" x")[1]);
       int totalNuevo;
       
       if(numProductos.equals("")) numProductos = "1";
       totalNuevo = totalActual + Integer.parseInt(numProductos);
       
       actualizacion = productoActual.split(" x")[0] +" x"+ String.valueOf(totalNuevo);
       model.set(indice, actualizacion);
   }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LayeredBotonera;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PaneProductosBebidas;
    private javax.swing.JPanel PaneProductosCalientes;
    private javax.swing.JPanel PaneProductosFrios;
    private javax.swing.JPanel PaneProductosIndex;
    private javax.swing.JPanel PanelNumeros;
    private javax.swing.JList<String> Ticket;
    private javax.swing.JPanel Total;
    private javax.swing.JButton atras;
    private javax.swing.JButton atras1;
    private javax.swing.JButton atras2;
    private javax.swing.JLabel bebidaCerveza;
    private javax.swing.JLabel bebidaCocaCola;
    private javax.swing.JLabel bebidaLimon;
    private javax.swing.JLabel bebidaNaranja;
    private javax.swing.JButton botonBebidas;
    private javax.swing.JButton botonBorrarTodo;
    private javax.swing.JButton botonBorrarUno;
    private javax.swing.JButton botonCalientes;
    private javax.swing.JButton botonCobrar;
    private javax.swing.JButton botonFactura;
    private javax.swing.JButton botonFrios;
    private javax.swing.JButton btnAdministracion;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton calc0;
    private javax.swing.JButton calc1;
    private javax.swing.JButton calc2;
    private javax.swing.JButton calc3;
    private javax.swing.JButton calc4;
    private javax.swing.JButton calc5;
    private javax.swing.JButton calc6;
    private javax.swing.JButton calc7;
    private javax.swing.JButton calc8;
    private javax.swing.JButton calc9;
    private javax.swing.JLabel calienteJamonQueso;
    private javax.swing.JLabel calienteJamonQueso1;
    private javax.swing.JLabel calienteSalmon;
    private javax.swing.JLabel calienteSalmon1;
    private javax.swing.JLabel calienteSolomillo;
    private javax.swing.JLabel calienteSolomillo1;
    private javax.swing.JButton cerrarAplicacion;
    private javax.swing.JLabel friosAzulRucula;
    private javax.swing.JLabel friosBaconHuevo;
    private javax.swing.JLabel friosCurry;
    private javax.swing.JLabel friosPavoManzana;
    private javax.swing.JLabel friosQuesoTom;
    private javax.swing.JLabel friosQuesoTom6;
    private javax.swing.JLabel friosQuesoTom7;
    private javax.swing.JLabel friosSerrano;
    private javax.swing.JLabel friosVegetal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelBotonesControl;
    private javax.swing.JTextField totalIva;
    private javax.swing.JTextField totalPrecioVenta;
    // End of variables declaration//GEN-END:variables
}
